/**
 * Emoji data organized by categories for the emoji picker.
 * Each emoji includes its Unicode character and a short name for search.
 */

export interface EmojiDef {
  char: string
  name: string
  keywords?: string[]
}

export interface EmojiCategory {
  label: string
  icon: string
  emojis: EmojiDef[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    label: '表情',
    icon: '😀',
    emojis: [
      { char: '😀', name: 'grinning', keywords: ['smile', 'happy'] },
      { char: '😃', name: 'smiley', keywords: ['smile', 'happy'] },
      { char: '😄', name: 'smile', keywords: ['happy', 'joy'] },
      { char: '😁', name: 'grin', keywords: ['smile', 'happy'] },
      { char: '😆', name: 'laughing', keywords: ['laugh', 'happy'] },
      { char: '😅', name: 'sweat smile', keywords: ['nervous', 'awkward'] },
      { char: '🤣', name: 'rofl', keywords: ['laugh', 'funny'] },
      { char: '😂', name: 'joy', keywords: ['laugh', 'tears'] },
      { char: '🙂', name: 'slight smile', keywords: ['smile'] },
      { char: '🙃', name: 'upside down', keywords: ['silly'] },
      { char: '😉', name: 'wink', keywords: ['wink', 'flirt'] },
      { char: '😊', name: 'blush', keywords: ['happy', 'shy'] },
      { char: '😇', name: 'innocent', keywords: ['angel', 'halo'] },
      { char: '🥰', name: 'in love', keywords: ['love', 'hearts'] },
      { char: '😍', name: 'heart eyes', keywords: ['love', 'crush'] },
      { char: '🤩', name: 'star eyes', keywords: ['excited', 'wow'] },
      { char: '😘', name: 'kiss', keywords: ['love', 'kiss'] },
      { char: '😗', name: 'kissing', keywords: ['kiss'] },
      { char: '😚', name: 'kiss closed', keywords: ['kiss'] },
      { char: '😋', name: 'yum', keywords: ['tasty', 'tongue'] },
      { char: '😛', name: 'tongue out', keywords: ['silly', 'playful'] },
      { char: '😜', name: 'wink tongue', keywords: ['silly', 'crazy'] },
      { char: '🤪', name: 'zany', keywords: ['crazy', 'silly'] },
      { char: '😝', name: 'squint tongue', keywords: ['silly', 'gross'] },
      { char: '🤑', name: 'money face', keywords: ['money', 'rich'] },
      { char: '🤗', name: 'hug', keywords: ['hug', 'warm'] },
      { char: '🤭', name: 'hand over mouth', keywords: ['oops', 'secret'] },
      { char: '🤫', name: 'shushing', keywords: ['quiet', 'secret'] },
      { char: '🤔', name: 'thinking', keywords: ['think', 'hmm'] },
      { char: '🤐', name: 'zipper mouth', keywords: ['secret', 'quiet'] },
      { char: '🤨', name: 'raised eyebrow', keywords: ['suspicious', 'hmm'] },
      { char: '😐', name: 'neutral', keywords: ['meh', 'blank'] },
      { char: '😑', name: 'expressionless', keywords: ['meh', 'blank'] },
      { char: '😶', name: 'no mouth', keywords: ['silent', 'speechless'] },
      { char: '😏', name: 'smirk', keywords: ['smug', 'flirt'] },
      { char: '😒', name: 'unamused', keywords: ['bored', 'annoyed'] },
      { char: '🙄', name: 'eye roll', keywords: ['annoyed', 'whatever'] },
      { char: '😬', name: 'grimacing', keywords: ['nervous', 'awkward'] },
      { char: '🤥', name: 'lying', keywords: ['lie', 'pinocchio'] },
      { char: '😌', name: 'relieved', keywords: ['relaxed', 'peace'] },
      { char: '😔', name: 'pensive', keywords: ['sad', 'thinking'] },
      { char: '😪', name: 'sleepy', keywords: ['tired', 'sleep'] },
      { char: '🤤', name: 'drooling', keywords: ['hungry', 'desire'] },
      { char: '😴', name: 'sleeping', keywords: ['sleep', 'zzz'] },
      { char: '😷', name: 'mask', keywords: ['sick', 'mask'] },
      { char: '🤒', name: 'sick', keywords: ['sick', 'fever'] },
      { char: '🤕', name: 'injured', keywords: ['hurt', 'bandage'] },
      { char: '🤢', name: 'nauseated', keywords: ['sick', 'gross'] },
      { char: '🤮', name: 'vomiting', keywords: ['sick', 'gross'] },
      { char: '🤧', name: 'sneezing', keywords: ['sick', 'cold'] },
      { char: '🥵', name: 'hot', keywords: ['hot', 'sweat'] },
      { char: '🥶', name: 'cold', keywords: ['cold', 'freeze'] },
      { char: '🥴', name: 'woozy', keywords: ['drunk', 'dizzy'] },
      { char: '😵', name: 'dizzy', keywords: ['dizzy', 'dead'] },
      { char: '🤯', name: 'mind blown', keywords: ['explosion', 'wow'] },
      { char: '🤠', name: 'cowboy', keywords: ['cowboy', 'hat'] },
      { char: '🥳', name: 'party', keywords: ['party', 'celebrate'] },
      { char: '😎', name: 'cool', keywords: ['cool', 'sunglasses'] },
      { char: '🤓', name: 'nerd', keywords: ['nerd', 'geek'] },
      { char: '🧐', name: 'monocle', keywords: ['fancy', 'examine'] },
      { char: '😕', name: 'confused', keywords: ['confused', 'huh'] },
      { char: '😟', name: 'worried', keywords: ['worried', 'concern'] },
      { char: '🙁', name: 'slight frown', keywords: ['sad', 'frown'] },
      { char: '☹️', name: 'frown', keywords: ['sad', 'frown'] },
      { char: '😮', name: 'open mouth', keywords: ['surprised', 'wow'] },
      { char: '😯', name: 'hushed', keywords: ['surprised', 'quiet'] },
      { char: '😲', name: 'astonished', keywords: ['surprised', 'wow'] },
      { char: '😳', name: 'flushed', keywords: ['embarrassed', 'shy'] },
      { char: '🥺', name: 'pleading', keywords: ['puppy eyes', 'begging'] },
      { char: '😦', name: 'frowning open', keywords: ['sad', 'frown'] },
      { char: '😧', name: 'anguished', keywords: ['sad', 'pain'] },
      { char: '😨', name: 'fearful', keywords: ['scared', 'fear'] },
      { char: '😰', name: 'anxious', keywords: ['worried', 'sweat'] },
      { char: '😥', name: 'sad relieved', keywords: ['sad', 'phew'] },
      { char: '😢', name: 'crying', keywords: ['sad', 'tears'] },
      { char: '😭', name: 'sobbing', keywords: ['sad', 'cry'] },
      { char: '😱', name: 'scream', keywords: ['scared', 'shock'] },
      { char: '😖', name: 'confounded', keywords: ['frustrated', 'ugh'] },
      { char: '😣', name: 'persevere', keywords: ['struggling', 'ugh'] },
      { char: '😞', name: 'disappointed', keywords: ['sad', 'let down'] },
      { char: '😓', name: 'downcast sweat', keywords: ['hard work', 'tired'] },
      { char: '😩', name: 'weary', keywords: ['tired', 'exhausted'] },
      { char: '😫', name: 'tired', keywords: ['tired', 'exhausted'] },
      { char: '🥱', name: 'yawning', keywords: ['tired', 'sleepy'] },
      { char: '😤', name: 'triumph', keywords: ['angry', 'steam'] },
      { char: '😡', name: 'rage', keywords: ['angry', 'mad'] },
      { char: '😠', name: 'angry', keywords: ['mad', 'upset'] },
      { char: '🤬', name: 'cursing', keywords: ['swear', 'angry'] },
      { char: '👿', name: 'imp', keywords: ['devil', 'angry'] },
      { char: '😈', name: 'smiling imp', keywords: ['devil', 'mischief'] },
      { char: '💀', name: 'skull', keywords: ['dead', 'death'] },
      { char: '☠️', name: 'skull crossbones', keywords: ['pirate', 'death'] },
      { char: '💩', name: 'poop', keywords: ['poop', 'funny'] },
      { char: '🤡', name: 'clown', keywords: ['clown', 'funny'] },
      { char: '👻', name: 'ghost', keywords: ['ghost', 'spooky'] },
      { char: '👽', name: 'alien', keywords: ['alien', 'ufo'] },
      { char: '👾', name: 'alien monster', keywords: ['game', 'alien'] },
      { char: '🤖', name: 'robot', keywords: ['robot', 'ai'] },
    ],
  },
  {
    label: '手势',
    icon: '👍',
    emojis: [
      { char: '👍', name: 'thumbs up', keywords: ['yes', 'like', 'good'] },
      { char: '👎', name: 'thumbs down', keywords: ['no', 'dislike', 'bad'] },
      { char: '👏', name: 'clap', keywords: ['clap', 'applause'] },
      { char: '🙌', name: 'raised hands', keywords: ['praise', 'celebration'] },
      { char: '👐', name: 'open hands', keywords: ['open', 'hug'] },
      { char: '🤲', name: 'palms up', keywords: ['pray', 'dua'] },
      { char: '🤝', name: 'handshake', keywords: ['deal', 'agree'] },
      { char: '🙏', name: 'pray', keywords: ['please', 'thanks', 'pray'] },
      { char: '✌️', name: 'peace', keywords: ['victory', 'peace'] },
      { char: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope'] },
      { char: '🤟', name: 'love you', keywords: ['love', 'rock'] },
      { char: '🤘', name: 'rock on', keywords: ['rock', 'music'] },
      { char: '👌', name: 'ok', keywords: ['ok', 'perfect'] },
      { char: '🤏', name: 'pinching', keywords: ['little', 'pinch'] },
      { char: '👈', name: 'point left', keywords: ['left', 'point'] },
      { char: '👉', name: 'point right', keywords: ['right', 'point'] },
      { char: '👆', name: 'point up', keywords: ['up', 'point'] },
      { char: '👇', name: 'point down', keywords: ['down', 'point'] },
      { char: '☝️', name: 'index up', keywords: ['one', 'point'] },
      { char: '✋', name: 'raised hand', keywords: ['stop', 'high five'] },
      { char: '🤚', name: 'raised back', keywords: ['hand', 'stop'] },
      { char: '🖐️', name: 'hand fingers', keywords: ['hand', 'five'] },
      { char: '🖖', name: 'vulcan', keywords: ['spock', 'star trek'] },
      { char: '👋', name: 'wave', keywords: ['wave', 'hello', 'bye'] },
      { char: '🤙', name: 'call me', keywords: ['call', 'phone'] },
      { char: '💪', name: 'flex', keywords: ['strong', 'muscle'] },
      { char: '🦾', name: 'mechanical arm', keywords: ['robot', 'bionic'] },
      { char: '🦿', name: 'mechanical leg', keywords: ['robot', 'bionic'] },
      { char: '🦶', name: 'foot', keywords: ['foot'] },
      { char: '👂', name: 'ear', keywords: ['listen', 'hear'] },
      { char: '🦻', name: 'hearing aid', keywords: ['ear', 'aid'] },
      { char: '👃', name: 'nose', keywords: ['nose', 'smell'] },
      { char: '🧠', name: 'brain', keywords: ['smart', 'brain'] },
      { char: '👀', name: 'eyes', keywords: ['look', 'eyes'] },
      { char: '👁️', name: 'eye', keywords: ['eye', 'see'] },
      { char: '👅', name: 'tongue', keywords: ['tongue', 'taste'] },
      { char: '👄', name: 'lips', keywords: ['lips', 'kiss'] },
      { char: '💋', name: 'kiss mark', keywords: ['kiss', 'love'] },
    ],
  },
  {
    label: '爱心',
    icon: '❤️',
    emojis: [
      { char: '❤️', name: 'red heart', keywords: ['love', 'heart'] },
      { char: '🧡', name: 'orange heart', keywords: ['love', 'orange'] },
      { char: '💛', name: 'yellow heart', keywords: ['love', 'yellow'] },
      { char: '💚', name: 'green heart', keywords: ['love', 'green'] },
      { char: '💙', name: 'blue heart', keywords: ['love', 'blue'] },
      { char: '💜', name: 'purple heart', keywords: ['love', 'purple'] },
      { char: '🖤', name: 'black heart', keywords: ['love', 'dark'] },
      { char: '🤍', name: 'white heart', keywords: ['love', 'white'] },
      { char: '🤎', name: 'brown heart', keywords: ['love', 'brown'] },
      { char: '💔', name: 'broken heart', keywords: ['sad', 'breakup'] },
      { char: '❣️', name: 'heart exclamation', keywords: ['love', 'exclaim'] },
      { char: '💕', name: 'two hearts', keywords: ['love', 'couple'] },
      { char: '💞', name: 'revolving hearts', keywords: ['love', 'spinning'] },
      { char: '💓', name: 'beating heart', keywords: ['love', 'beat'] },
      { char: '💗', name: 'growing heart', keywords: ['love', 'grow'] },
      { char: '💖', name: 'sparkling heart', keywords: ['love', 'sparkle'] },
      { char: '💘', name: 'cupid heart', keywords: ['love', 'arrow'] },
      { char: '💝', name: 'heart ribbon', keywords: ['love', 'gift'] },
      { char: '💟', name: 'heart decoration', keywords: ['love', 'decor'] },
      { char: '💌', name: 'love letter', keywords: ['love', 'letter'] },
      { char: '😻', name: 'heart cat', keywords: ['love', 'cat'] },
      { char: '💑', name: 'couple heart', keywords: ['love', 'couple'] },
      { char: '💏', name: 'couple kiss', keywords: ['love', 'kiss'] },
    ],
  },
  {
    label: '自然',
    icon: '🔥',
    emojis: [
      { char: '🔥', name: 'fire', keywords: ['hot', 'lit', 'awesome'] },
      { char: '⭐', name: 'star', keywords: ['star', 'favorite'] },
      { char: '🌟', name: 'glowing star', keywords: ['star', 'shine'] },
      { char: '✨', name: 'sparkles', keywords: ['sparkle', 'magic'] },
      { char: '💫', name: 'dizzy', keywords: ['sparkle', 'dizzy'] },
      { char: '🎉', name: 'party popper', keywords: ['party', 'celebrate'] },
      { char: '🎊', name: 'confetti ball', keywords: ['party', 'celebrate'] },
      { char: '🎈', name: 'balloon', keywords: ['party', 'balloon'] },
      { char: '🎁', name: 'gift', keywords: ['gift', 'present'] },
      { char: '💯', name: 'hundred', keywords: ['100', 'perfect', 'score'] },
      { char: '💥', name: 'collision', keywords: ['explosion', 'boom'] },
      { char: '💢', name: 'anger', keywords: ['angry', 'mad'] },
      { char: '💦', name: 'sweat drops', keywords: ['water', 'sweat'] },
      { char: '💨', name: 'dash', keywords: ['fast', 'speed'] },
      { char: '🕳️', name: 'hole', keywords: ['hole', 'portal'] },
      { char: '💣', name: 'bomb', keywords: ['bomb', 'explosion'] },
      { char: '💤', name: 'zzz', keywords: ['sleep', 'tired'] },
      { char: '🌙', name: 'moon', keywords: ['night', 'moon'] },
      { char: '☀️', name: 'sun', keywords: ['sun', 'sunny'] },
      { char: '🌈', name: 'rainbow', keywords: ['rainbow', 'colorful'] },
      { char: '☁️', name: 'cloud', keywords: ['cloud', 'weather'] },
      { char: '⛈️', name: 'storm', keywords: ['storm', 'rain'] },
      { char: '🌧️', name: 'rain', keywords: ['rain', 'weather'] },
      { char: '❄️', name: 'snowflake', keywords: ['snow', 'cold'] },
      { char: '☄️', name: 'comet', keywords: ['comet', 'space'] },
      { char: '🌊', name: 'wave', keywords: ['wave', 'ocean'] },
      { char: '🎄', name: 'christmas tree', keywords: ['christmas', 'tree'] },
      { char: '🌸', name: 'cherry blossom', keywords: ['flower', 'spring'] },
      { char: '🌹', name: 'rose', keywords: ['flower', 'love'] },
      { char: '🌻', name: 'sunflower', keywords: ['flower', 'sun'] },
      { char: '🌺', name: 'hibiscus', keywords: ['flower', 'tropical'] },
      { char: '🍀', name: 'four leaf clover', keywords: ['luck', 'clover'] },
      { char: '☘️', name: 'shamrock', keywords: ['clover', 'irish'] },
    ],
  },
  {
    label: '物品',
    icon: '💻',
    emojis: [
      { char: '💻', name: 'laptop', keywords: ['computer', 'work'] },
      { char: '🖥️', name: 'desktop', keywords: ['computer', 'pc'] },
      { char: '⌨️', name: 'keyboard', keywords: ['keyboard', 'type'] },
      { char: '🖱️', name: 'mouse', keywords: ['mouse', 'click'] },
      { char: '🖨️', name: 'printer', keywords: ['print', 'printer'] },
      { char: '📱', name: 'phone', keywords: ['phone', 'mobile'] },
      { char: '📲', name: 'phone arrow', keywords: ['phone', 'call'] },
      { char: '☎️', name: 'telephone', keywords: ['phone', 'call'] },
      { char: '📞', name: 'phone receiver', keywords: ['phone', 'call'] },
      { char: '📟', name: 'pager', keywords: ['pager', 'old'] },
      { char: '📠', name: 'fax', keywords: ['fax', 'old'] },
      { char: '🔋', name: 'battery', keywords: ['battery', 'power'] },
      { char: '🔌', name: 'plug', keywords: ['plug', 'power'] },
      { char: '💡', name: 'light bulb', keywords: ['idea', 'light'] },
      { char: '🔦', name: 'flashlight', keywords: ['light', 'torch'] },
      { char: '🕯️', name: 'candle', keywords: ['candle', 'light'] },
      { char: '🗑️', name: 'wastebasket', keywords: ['trash', 'delete'] },
      { char: '📄', name: 'document', keywords: ['file', 'doc'] },
      { char: '📃', name: 'page curl', keywords: ['document', 'page'] },
      { char: '📋', name: 'clipboard', keywords: ['clipboard', 'copy'] },
      { char: '📊', name: 'bar chart', keywords: ['chart', 'data'] },
      { char: '📈', name: 'chart up', keywords: ['chart', 'growth'] },
      { char: '📉', name: 'chart down', keywords: ['chart', 'loss'] },
      { char: '📁', name: 'folder', keywords: ['folder', 'file'] },
      { char: '📂', name: 'open folder', keywords: ['folder', 'open'] },
      { char: '🗂️', name: 'index dividers', keywords: ['folder', 'organize'] },
      { char: '📅', name: 'calendar', keywords: ['calendar', 'date'] },
      { char: '📆', name: 'tear-off calendar', keywords: ['calendar', 'date'] },
      { char: '🗓️', name: 'spiral calendar', keywords: ['calendar', 'date'] },
      { char: '📇', name: 'card index', keywords: ['card', 'index'] },
      { char: '🗃️', name: 'card file', keywords: ['file', 'box'] },
      { char: '📋', name: 'clipboard', keywords: ['clipboard', 'tasks'] },
      { char: '🔒', name: 'locked', keywords: ['lock', 'secure'] },
      { char: '🔓', name: 'unlocked', keywords: ['lock', 'open'] },
      { char: '🔏', name: 'lock pen', keywords: ['lock', 'privacy'] },
      { char: '🔐', name: 'lock key', keywords: ['lock', 'secure'] },
      { char: '🔑', name: 'key', keywords: ['key', 'password'] },
      { char: '🗝️', name: 'old key', keywords: ['key', 'old'] },
      { char: '🔨', name: 'hammer', keywords: ['hammer', 'tool'] },
      { char: '⚒️', name: 'hammer pick', keywords: ['tool', 'mine'] },
      { char: '🛠️', name: 'hammer wrench', keywords: ['tool', 'fix'] },
      { char: '⛏️', name: 'pick', keywords: ['pick', 'mine'] },
      { char: '🔧', name: 'wrench', keywords: ['wrench', 'tool'] },
      { char: '🗡️', name: 'dagger', keywords: ['weapon', 'knife'] },
      { char: '⚔️', name: 'swords', keywords: ['weapon', 'fight'] },
      { char: '🔫', name: 'gun', keywords: ['weapon', 'shoot'] },
      { char: '🛡️', name: 'shield', keywords: ['shield', 'defense'] },
      { char: '🔮', name: 'crystal ball', keywords: ['magic', 'fortune'] },
      { char: '🧿', name: 'nazar', keywords: ['evil eye', 'amulet'] },
    ],
  },
  {
    label: '食物',
    icon: '🍕',
    emojis: [
      { char: '🍕', name: 'pizza', keywords: ['pizza', 'food'] },
      { char: '🍔', name: 'burger', keywords: ['burger', 'food'] },
      { char: '🍟', name: 'fries', keywords: ['fries', 'food'] },
      { char: '🌭', name: 'hot dog', keywords: ['hotdog', 'food'] },
      { char: '🍿', name: 'popcorn', keywords: ['popcorn', 'movie'] },
      { char: '🧂', name: 'salt', keywords: ['salt', 'seasoning'] },
      { char: '🥚', name: 'egg', keywords: ['egg', 'food'] },
      { char: '🍳', name: 'cooking', keywords: ['cook', 'breakfast'] },
      { char: '🧇', name: 'waffle', keywords: ['waffle', 'breakfast'] },
      { char: '🥞', name: 'pancakes', keywords: ['pancake', 'breakfast'] },
      { char: '🧈', name: 'butter', keywords: ['butter', 'food'] },
      { char: '🍞', name: 'bread', keywords: ['bread', 'food'] },
      { char: '🥐', name: 'croissant', keywords: ['croissant', 'pastry'] },
      { char: '🥨', name: 'pretzel', keywords: ['pretzel', 'snack'] },
      { char: '🥯', name: 'bagel', keywords: ['bagel', 'breakfast'] },
      { char: '🥞', name: 'pancakes', keywords: ['pancake', 'food'] },
      { char: '🧀', name: 'cheese', keywords: ['cheese', 'food'] },
      { char: '🍖', name: 'meat', keywords: ['meat', 'food'] },
      { char: '🍗', name: 'chicken leg', keywords: ['chicken', 'food'] },
      { char: '🥩', name: 'steak', keywords: ['steak', 'meat'] },
      { char: '🥓', name: 'bacon', keywords: ['bacon', 'food'] },
      { char: '🍝', name: 'spaghetti', keywords: ['pasta', 'food'] },
      { char: '🍜', name: 'ramen', keywords: ['ramen', 'noodle'] },
      { char: '🍲', name: 'stew', keywords: ['stew', 'food'] },
      { char: '🍛', name: 'curry', keywords: ['curry', 'rice'] },
      { char: '🍣', name: 'sushi', keywords: ['sushi', 'japanese'] },
      { char: '🍱', name: 'bento', keywords: ['bento', 'lunch'] },
      { char: '🍙', name: 'rice ball', keywords: ['rice', 'onigiri'] },
      { char: '🍚', name: 'rice', keywords: ['rice', 'food'] },
      { char: '🍘', name: 'rice cracker', keywords: ['rice', 'cracker'] },
      { char: '🍤', name: 'shrimp', keywords: ['shrimp', 'tempura'] },
      { char: '🍩', name: 'doughnut', keywords: ['donut', 'sweet'] },
      { char: '🍪', name: 'cookie', keywords: ['cookie', 'sweet'] },
      { char: '🎂', name: 'cake', keywords: ['cake', 'birthday'] },
      { char: '🍰', name: 'cake slice', keywords: ['cake', 'dessert'] },
      { char: '🧁', name: 'cupcake', keywords: ['cupcake', 'sweet'] },
      { char: '🍫', name: 'chocolate', keywords: ['chocolate', 'sweet'] },
      { char: '🍬', name: 'candy', keywords: ['candy', 'sweet'] },
      { char: '🍭', name: 'lollipop', keywords: ['lollipop', 'candy'] },
      { char: '🍮', name: 'custard', keywords: ['custard', 'dessert'] },
      { char: '🍯', name: 'honey', keywords: ['honey', 'sweet'] },
      { char: '🍼', name: 'baby bottle', keywords: ['baby', 'milk'] },
      { char: '🥛', name: 'milk', keywords: ['milk', 'drink'] },
      { char: '☕', name: 'coffee', keywords: ['coffee', 'caffeine'] },
      { char: '🍵', name: 'tea', keywords: ['tea', 'drink'] },
      { char: '🧃', name: 'juice', keywords: ['juice', 'drink'] },
      { char: '🥤', name: 'soda cup', keywords: ['soda', 'drink'] },
      { char: '🧋', name: 'bubble tea', keywords: ['bubble tea', 'boba'] },
      { char: '🍶', name: 'sake', keywords: ['sake', 'alcohol'] },
      { char: '🍺', name: 'beer', keywords: ['beer', 'alcohol'] },
      { char: '🍻', name: 'beers', keywords: ['beer', 'cheers'] },
      { char: '🥂', name: 'clink', keywords: ['cheers', 'celebrate'] },
      { char: '🍷', name: 'wine', keywords: ['wine', 'drink'] },
      { char: '🥃', name: 'whiskey', keywords: ['whiskey', 'drink'] },
      { char: '🍸', name: 'cocktail', keywords: ['cocktail', 'drink'] },
      { char: '🍹', name: 'tropical drink', keywords: ['drink', 'tropical'] },
      { char: '🧊', name: 'ice', keywords: ['ice', 'cold'] },
      { char: '🍾', name: 'champagne', keywords: ['champagne', 'celebrate'] },
      { char: '🧉', name: 'mate', keywords: ['mate', 'drink'] },
    ],
  },
  {
    label: '运动',
    icon: '⚽',
    emojis: [
      { char: '⚽', name: 'soccer', keywords: ['soccer', 'football'] },
      { char: '🏀', name: 'basketball', keywords: ['basketball', 'nba'] },
      { char: '🏈', name: 'football', keywords: ['football', 'nfl'] },
      { char: '⚾', name: 'baseball', keywords: ['baseball', 'mlb'] },
      { char: '🥎', name: 'softball', keywords: ['softball', 'ball'] },
      { char: '🎾', name: 'tennis', keywords: ['tennis', 'sport'] },
      { char: '🏐', name: 'volleyball', keywords: ['volleyball', 'sport'] },
      { char: '🏉', name: 'rugby', keywords: ['rugby', 'sport'] },
      { char: '🥏', name: 'frisbee', keywords: ['frisbee', 'disc'] },
      { char: '🎱', name: 'pool', keywords: ['pool', 'billiards'] },
      { char: '🏓', name: 'ping pong', keywords: ['ping pong', 'table tennis'] },
      { char: '🏸', name: 'badminton', keywords: ['badminton', 'sport'] },
      { char: '🏒', name: 'hockey', keywords: ['hockey', 'ice'] },
      { char: '🏑', name: 'field hockey', keywords: ['hockey', 'field'] },
      { char: '🥍', name: 'lacrosse', keywords: ['lacrosse', 'sport'] },
      { char: '🏏', name: 'cricket', keywords: ['cricket', 'sport'] },
      { char: '⛳', name: 'golf', keywords: ['golf', 'hole'] },
      { char: '🏹', name: 'archery', keywords: ['archery', 'bow'] },
      { char: '🎣', name: 'fishing', keywords: ['fishing', 'fish'] },
      { char: '🤿', name: 'diving mask', keywords: ['diving', 'snorkel'] },
      { char: '🥊', name: 'boxing glove', keywords: ['boxing', 'fight'] },
      { char: '🥋', name: 'martial arts', keywords: ['karate', 'judo'] },
      { char: '⛸️', name: 'ice skate', keywords: ['ice skate', 'skating'] },
      { char: '🎿', name: 'skiing', keywords: ['ski', 'snow'] },
      { char: '🛷', name: 'sled', keywords: ['sled', 'snow'] },
      { char: '🏂', name: 'snowboard', keywords: ['snowboard', 'snow'] },
      { char: '🏋️', name: 'weightlifting', keywords: ['gym', 'lift'] },
      { char: '🤼', name: 'wrestling', keywords: ['wrestle', 'fight'] },
      { char: '🤸', name: 'cartwheel', keywords: ['gymnastics', 'flip'] },
      { char: '⛹️', name: 'basketball person', keywords: ['basketball', 'dribble'] },
      { char: '🤺', name: 'fencing', keywords: ['fencing', 'sword'] },
      { char: '🎲', name: 'die', keywords: ['dice', 'game'] },
      { char: '♟️', name: 'chess pawn', keywords: ['chess', 'board game'] },
      { char: '🎯', name: 'bullseye', keywords: ['target', 'dart'] },
      { char: '🎮', name: 'gamepad', keywords: ['game', 'controller'] },
      { char: '🕹️', name: 'joystick', keywords: ['game', 'arcade'] },
      { char: '🎰', name: 'slot machine', keywords: ['slot', 'casino'] },
      { char: '🏆', name: 'trophy', keywords: ['trophy', 'win'] },
      { char: '🥇', name: 'gold medal', keywords: ['gold', 'first'] },
      { char: '🥈', name: 'silver medal', keywords: ['silver', 'second'] },
      { char: '🥉', name: 'bronze medal', keywords: ['bronze', 'third'] },
    ],
  },
  {
    label: '动物',
    icon: '🐱',
    emojis: [
      { char: '🐱', name: 'cat', keywords: ['cat', 'kitten'] },
      { char: '🐶', name: 'dog', keywords: ['dog', 'puppy'] },
      { char: '🐭', name: 'mouse', keywords: ['mouse', 'rat'] },
      { char: '🐹', name: 'hamster', keywords: ['hamster', 'pet'] },
      { char: '🐰', name: 'rabbit', keywords: ['rabbit', 'bunny'] },
      { char: '🦊', name: 'fox', keywords: ['fox', 'animal'] },
      { char: '🐻', name: 'bear', keywords: ['bear', 'animal'] },
      { char: '🐼', name: 'panda', keywords: ['panda', 'animal'] },
      { char: '🐨', name: 'koala', keywords: ['koala', 'animal'] },
      { char: '🐯', name: 'tiger', keywords: ['tiger', 'animal'] },
      { char: '🦁', name: 'lion', keywords: ['lion', 'animal'] },
      { char: '🐮', name: 'cow', keywords: ['cow', 'animal'] },
      { char: '🐷', name: 'pig', keywords: ['pig', 'animal'] },
      { char: '🐸', name: 'frog', keywords: ['frog', 'animal'] },
      { char: '🐵', name: 'monkey', keywords: ['monkey', 'animal'] },
      { char: '🐔', name: 'chicken', keywords: ['chicken', 'bird'] },
      { char: '🐧', name: 'penguin', keywords: ['penguin', 'bird'] },
      { char: '🐦', name: 'bird', keywords: ['bird', 'animal'] },
      { char: '🐤', name: 'baby chick', keywords: ['chick', 'bird'] },
      { char: '🦆', name: 'duck', keywords: ['duck', 'bird'] },
      { char: '🦅', name: 'eagle', keywords: ['eagle', 'bird'] },
      { char: '🦉', name: 'owl', keywords: ['owl', 'bird'] },
      { char: '🦇', name: 'bat', keywords: ['bat', 'animal'] },
      { char: '🐺', name: 'wolf', keywords: ['wolf', 'animal'] },
      { char: '🐗', name: 'boar', keywords: ['boar', 'animal'] },
      { char: '🐴', name: 'horse', keywords: ['horse', 'animal'] },
      { char: '🦄', name: 'unicorn', keywords: ['unicorn', 'magic'] },
      { char: '🐝', name: 'bee', keywords: ['bee', 'insect'] },
      { char: '🐛', name: 'bug', keywords: ['bug', 'insect'] },
      { char: '🦋', name: 'butterfly', keywords: ['butterfly', 'insect'] },
      { char: '🐌', name: 'snail', keywords: ['snail', 'slow'] },
      { char: '🐞', name: 'ladybug', keywords: ['ladybug', 'insect'] },
      { char: '🐜', name: 'ant', keywords: ['ant', 'insect'] },
      { char: '🦟', name: 'mosquito', keywords: ['mosquito', 'insect'] },
      { char: '🦗', name: 'cricket', keywords: ['cricket', 'insect'] },
      { char: '🕷️', name: 'spider', keywords: ['spider', 'insect'] },
      { char: '🦂', name: 'scorpion', keywords: ['scorpion', 'insect'] },
      { char: '🐢', name: 'turtle', keywords: ['turtle', 'slow'] },
      { char: '🐍', name: 'snake', keywords: ['snake', 'reptile'] },
      { char: '🦎', name: 'lizard', keywords: ['lizard', 'reptile'] },
      { char: '🦖', name: 't-rex', keywords: ['dinosaur', 'trex'] },
      { char: '🦕', name: 'sauropod', keywords: ['dinosaur', 'long neck'] },
      { char: '🐙', name: 'octopus', keywords: ['octopus', 'sea'] },
      { char: '🦑', name: 'squid', keywords: ['squid', 'sea'] },
      { char: '🦐', name: 'shrimp', keywords: ['shrimp', 'seafood'] },
      { char: '🦞', name: 'lobster', keywords: ['lobster', 'seafood'] },
      { char: '🦀', name: 'crab', keywords: ['crab', 'seafood'] },
      { char: '🐠', name: 'tropical fish', keywords: ['fish', 'sea'] },
      { char: '🐟', name: 'fish', keywords: ['fish', 'sea'] },
      { char: '🐡', name: 'blowfish', keywords: ['blowfish', 'sea'] },
      { char: '🦈', name: 'shark', keywords: ['shark', 'sea'] },
      { char: '🐬', name: 'dolphin', keywords: ['dolphin', 'sea'] },
      { char: '🐳', name: 'whale', keywords: ['whale', 'sea'] },
      { char: '🐋', name: 'whale 2', keywords: ['whale', 'sea'] },
      { char: '🐊', name: 'crocodile', keywords: ['crocodile', 'reptile'] },
      { char: '🐅', name: 'tiger face', keywords: ['tiger', 'cat'] },
      { char: '🐆', name: 'leopard', keywords: ['leopard', 'cat'] },
      { char: '🦓', name: 'zebra', keywords: ['zebra', 'animal'] },
      { char: '🦍', name: 'gorilla', keywords: ['gorilla', 'ape'] },
      { char: '🦧', name: 'orangutan', keywords: ['orangutan', 'ape'] },
      { char: '🐘', name: 'elephant', keywords: ['elephant', 'animal'] },
      { char: '🦛', name: 'hippo', keywords: ['hippo', 'animal'] },
      { char: '🦏', name: 'rhino', keywords: ['rhino', 'animal'] },
      { char: '🐪', name: 'camel', keywords: ['camel', 'animal'] },
      { char: '🐫', name: 'bactrian camel', keywords: ['camel', 'animal'] },
      { char: '🦒', name: 'giraffe', keywords: ['giraffe', 'animal'] },
      { char: '🦘', name: 'kangaroo', keywords: ['kangaroo', 'australia'] },
      { char: '🐃', name: 'water buffalo', keywords: ['buffalo', 'animal'] },
      { char: '🐂', name: 'ox', keywords: ['ox', 'animal'] },
      { char: '🐄', name: 'cow face', keywords: ['cow', 'animal'] },
      { char: '🐎', name: 'horse racing', keywords: ['horse', 'race'] },
      { char: '🐖', name: 'pig face', keywords: ['pig', 'animal'] },
      { char: '🐏', name: 'ram', keywords: ['ram', 'animal'] },
      { char: '🐑', name: 'ewe', keywords: ['sheep', 'animal'] },
      { char: '🦙', name: 'llama', keywords: ['llama', 'animal'] },
      { char: '🐐', name: 'goat', keywords: ['goat', 'animal'] },
      { char: '🦌', name: 'deer', keywords: ['deer', 'animal'] },
      { char: '🐕', name: 'dog2', keywords: ['dog', 'pet'] },
      { char: '🐩', name: 'poodle', keywords: ['poodle', 'dog'] },
      { char: '🦮', name: 'guide dog', keywords: ['dog', 'guide'] },
      { char: '🐕‍🦺', name: 'service dog', keywords: ['dog', 'service'] },
      { char: '🐈', name: 'cat2', keywords: ['cat', 'pet'] },
      { char: '🐓', name: 'rooster', keywords: ['rooster', 'chicken'] },
      { char: '🦃', name: 'turkey', keywords: ['turkey', 'bird'] },
      { char: '🦚', name: 'peacock', keywords: ['peacock', 'bird'] },
      { char: '🦜', name: 'parrot', keywords: ['parrot', 'bird'] },
      { char: '🦢', name: 'swan', keywords: ['swan', 'bird'] },
      { char: '🦩', name: 'flamingo', keywords: ['flamingo', 'bird'] },
      { char: '🐇', name: 'rabbit face', keywords: ['rabbit', 'bunny'] },
      { char: '🦝', name: 'raccoon', keywords: ['raccoon', 'animal'] },
      { char: '🦡', name: 'badger', keywords: ['badger', 'animal'] },
      { char: '🐿️', name: 'chipmunk', keywords: ['chipmunk', 'squirrel'] },
      { char: '🦔', name: 'hedgehog', keywords: ['hedgehog', 'animal'] },
    ],
  },
  {
    label: '交通',
    icon: '🚗',
    emojis: [
      { char: '🚗', name: 'car', keywords: ['car', 'drive'] },
      { char: '🚕', name: 'taxi', keywords: ['taxi', 'cab'] },
      { char: '🚙', name: 'suv', keywords: ['suv', 'car'] },
      { char: '🚌', name: 'bus', keywords: ['bus', 'transport'] },
      { char: '🚎', name: 'trolleybus', keywords: ['bus', 'trolley'] },
      { char: '🏎️', name: 'race car', keywords: ['race', 'f1'] },
      { char: '🚓', name: 'police car', keywords: ['police', 'car'] },
      { char: '🚑', name: 'ambulance', keywords: ['ambulance', 'emergency'] },
      { char: '🚒', name: 'fire engine', keywords: ['fire', 'truck'] },
      { char: '🚐', name: 'minibus', keywords: ['bus', 'van'] },
      { char: '🚚', name: 'truck', keywords: ['truck', 'delivery'] },
      { char: '🚛', name: 'articulated lorry', keywords: ['truck', 'lorry'] },
      { char: '🚜', name: 'tractor', keywords: ['tractor', 'farm'] },
      { char: '🛴', name: 'scooter', keywords: ['scooter', 'kick'] },
      { char: '🚲', name: 'bicycle', keywords: ['bike', 'cycle'] },
      { char: '🛵', name: 'motor scooter', keywords: ['scooter', 'motor'] },
      { char: '🏍️', name: 'motorcycle', keywords: ['motorcycle', 'bike'] },
      { char: '🚅', name: 'bullet train', keywords: ['train', 'fast'] },
      { char: '🚄', name: 'high speed train', keywords: ['train', 'fast'] },
      { char: '🚂', name: 'steam locomotive', keywords: ['train', 'steam'] },
      { char: '🚃', name: 'train car', keywords: ['train', 'car'] },
      { char: '🚈', name: 'light rail', keywords: ['train', 'rail'] },
      { char: '✈️', name: 'airplane', keywords: ['plane', 'fly'] },
      { char: '🛩️', name: 'small plane', keywords: ['plane', 'fly'] },
      { char: '🚀', name: 'rocket', keywords: ['rocket', 'space'] },
      { char: '🛸', name: 'ufo', keywords: ['ufo', 'alien'] },
      { char: '🚁', name: 'helicopter', keywords: ['helicopter', 'fly'] },
      { char: '⛵', name: 'sailboat', keywords: ['boat', 'sail'] },
      { char: '🚤', name: 'speedboat', keywords: ['boat', 'speed'] },
      { char: '🛳️', name: 'passenger ship', keywords: ['ship', 'cruise'] },
      { char: '⛴️', name: 'ferry', keywords: ['ferry', 'boat'] },
      { char: '🚢', name: 'ship', keywords: ['ship', 'boat'] },
      { char: '🛥️', name: 'motor boat', keywords: ['boat', 'motor'] },
    ],
  },
]

/**
 * Flatten all emojis for search.
 */
export function searchEmoji(query: string): EmojiDef[] {
  const q = query.toLowerCase().trim()
  if (!q) return []
  const results: EmojiDef[] = []
  for (const cat of EMOJI_CATEGORIES) {
    for (const emoji of cat.emojis) {
      if (
        emoji.name.toLowerCase().includes(q) ||
        emoji.keywords?.some((kw) => kw.includes(q))
      ) {
        results.push(emoji)
      }
    }
  }
  return results.slice(0, 50)
}
